// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chainmon/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # proto/tx/message
type MsgCreateChainmon struct {
	Creator    string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name       string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MonClass   MonClass `protobuf:"varint,3,opt,name=monClass,proto3,enum=williamfeng323.chainmon.chainmon.MonClass" json:"monClass,omitempty"`
	Phase      Phase    `protobuf:"varint,4,opt,name=phase,proto3,enum=williamfeng323.chainmon.chainmon.Phase" json:"phase,omitempty"`
	Species    uint64   `protobuf:"varint,5,opt,name=species,proto3" json:"species,omitempty"`
	Databricks int64    `protobuf:"varint,6,opt,name=databricks,proto3" json:"databricks,omitempty"`
}

func (m *MsgCreateChainmon) Reset()         { *m = MsgCreateChainmon{} }
func (m *MsgCreateChainmon) String() string { return proto.CompactTextString(m) }
func (*MsgCreateChainmon) ProtoMessage()    {}
func (*MsgCreateChainmon) Descriptor() ([]byte, []int) {
	return fileDescriptor_b45dffb708d14765, []int{0}
}
func (m *MsgCreateChainmon) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateChainmon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateChainmon.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateChainmon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateChainmon.Merge(m, src)
}
func (m *MsgCreateChainmon) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateChainmon) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateChainmon.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateChainmon proto.InternalMessageInfo

func (m *MsgCreateChainmon) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateChainmon) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgCreateChainmon) GetMonClass() MonClass {
	if m != nil {
		return m.MonClass
	}
	return MonClass_BEAST
}

func (m *MsgCreateChainmon) GetPhase() Phase {
	if m != nil {
		return m.Phase
	}
	return Phase_BIT
}

func (m *MsgCreateChainmon) GetSpecies() uint64 {
	if m != nil {
		return m.Species
	}
	return 0
}

func (m *MsgCreateChainmon) GetDatabricks() int64 {
	if m != nil {
		return m.Databricks
	}
	return 0
}

type MsgCreateChainmonResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateChainmonResponse) Reset()         { *m = MsgCreateChainmonResponse{} }
func (m *MsgCreateChainmonResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateChainmonResponse) ProtoMessage()    {}
func (*MsgCreateChainmonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b45dffb708d14765, []int{1}
}
func (m *MsgCreateChainmonResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateChainmonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateChainmonResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateChainmonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateChainmonResponse.Merge(m, src)
}
func (m *MsgCreateChainmonResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateChainmonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateChainmonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateChainmonResponse proto.InternalMessageInfo

func (m *MsgCreateChainmonResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgUpdateChainmon struct {
	Creator    string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id         uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name       string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	MonClass   MonClass `protobuf:"varint,4,opt,name=monClass,proto3,enum=williamfeng323.chainmon.chainmon.MonClass" json:"monClass,omitempty"`
	Phase      Phase    `protobuf:"varint,5,opt,name=phase,proto3,enum=williamfeng323.chainmon.chainmon.Phase" json:"phase,omitempty"`
	Species    uint64   `protobuf:"varint,6,opt,name=species,proto3" json:"species,omitempty"`
	Databricks int64    `protobuf:"varint,7,opt,name=databricks,proto3" json:"databricks,omitempty"`
}

func (m *MsgUpdateChainmon) Reset()         { *m = MsgUpdateChainmon{} }
func (m *MsgUpdateChainmon) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateChainmon) ProtoMessage()    {}
func (*MsgUpdateChainmon) Descriptor() ([]byte, []int) {
	return fileDescriptor_b45dffb708d14765, []int{2}
}
func (m *MsgUpdateChainmon) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateChainmon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateChainmon.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateChainmon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateChainmon.Merge(m, src)
}
func (m *MsgUpdateChainmon) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateChainmon) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateChainmon.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateChainmon proto.InternalMessageInfo

func (m *MsgUpdateChainmon) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateChainmon) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgUpdateChainmon) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgUpdateChainmon) GetMonClass() MonClass {
	if m != nil {
		return m.MonClass
	}
	return MonClass_BEAST
}

func (m *MsgUpdateChainmon) GetPhase() Phase {
	if m != nil {
		return m.Phase
	}
	return Phase_BIT
}

func (m *MsgUpdateChainmon) GetSpecies() uint64 {
	if m != nil {
		return m.Species
	}
	return 0
}

func (m *MsgUpdateChainmon) GetDatabricks() int64 {
	if m != nil {
		return m.Databricks
	}
	return 0
}

type MsgUpdateChainmonResponse struct {
}

func (m *MsgUpdateChainmonResponse) Reset()         { *m = MsgUpdateChainmonResponse{} }
func (m *MsgUpdateChainmonResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateChainmonResponse) ProtoMessage()    {}
func (*MsgUpdateChainmonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b45dffb708d14765, []int{3}
}
func (m *MsgUpdateChainmonResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateChainmonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateChainmonResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateChainmonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateChainmonResponse.Merge(m, src)
}
func (m *MsgUpdateChainmonResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateChainmonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateChainmonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateChainmonResponse proto.InternalMessageInfo

type MsgDeleteChainmon struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgDeleteChainmon) Reset()         { *m = MsgDeleteChainmon{} }
func (m *MsgDeleteChainmon) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteChainmon) ProtoMessage()    {}
func (*MsgDeleteChainmon) Descriptor() ([]byte, []int) {
	return fileDescriptor_b45dffb708d14765, []int{4}
}
func (m *MsgDeleteChainmon) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteChainmon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteChainmon.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteChainmon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteChainmon.Merge(m, src)
}
func (m *MsgDeleteChainmon) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteChainmon) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteChainmon.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteChainmon proto.InternalMessageInfo

func (m *MsgDeleteChainmon) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteChainmon) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgDeleteChainmonResponse struct {
}

func (m *MsgDeleteChainmonResponse) Reset()         { *m = MsgDeleteChainmonResponse{} }
func (m *MsgDeleteChainmonResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteChainmonResponse) ProtoMessage()    {}
func (*MsgDeleteChainmonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b45dffb708d14765, []int{5}
}
func (m *MsgDeleteChainmonResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteChainmonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteChainmonResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteChainmonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteChainmonResponse.Merge(m, src)
}
func (m *MsgDeleteChainmonResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteChainmonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteChainmonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteChainmonResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateChainmon)(nil), "williamfeng323.chainmon.chainmon.MsgCreateChainmon")
	proto.RegisterType((*MsgCreateChainmonResponse)(nil), "williamfeng323.chainmon.chainmon.MsgCreateChainmonResponse")
	proto.RegisterType((*MsgUpdateChainmon)(nil), "williamfeng323.chainmon.chainmon.MsgUpdateChainmon")
	proto.RegisterType((*MsgUpdateChainmonResponse)(nil), "williamfeng323.chainmon.chainmon.MsgUpdateChainmonResponse")
	proto.RegisterType((*MsgDeleteChainmon)(nil), "williamfeng323.chainmon.chainmon.MsgDeleteChainmon")
	proto.RegisterType((*MsgDeleteChainmonResponse)(nil), "williamfeng323.chainmon.chainmon.MsgDeleteChainmonResponse")
}

func init() { proto.RegisterFile("chainmon/tx.proto", fileDescriptor_b45dffb708d14765) }

var fileDescriptor_b45dffb708d14765 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x3f, 0x4b, 0xfb, 0x40,
	0x18, 0xc7, 0x7b, 0x49, 0xda, 0xfe, 0x7e, 0x37, 0x14, 0x7a, 0x8b, 0xb1, 0x42, 0x08, 0x59, 0x0c,
	0x0a, 0x29, 0x34, 0xa3, 0x74, 0xb1, 0xe2, 0x16, 0x90, 0x80, 0x8b, 0xdb, 0x35, 0x39, 0xd3, 0xc3,
	0xfc, 0x23, 0x17, 0xb1, 0xae, 0x7d, 0x05, 0x22, 0xbe, 0x28, 0xc7, 0x8e, 0x8e, 0xd2, 0xbe, 0x11,
	0xc9, 0xb5, 0x89, 0x26, 0xad, 0x36, 0x54, 0xb7, 0xcb, 0x73, 0xf7, 0x79, 0xf2, 0xe5, 0x73, 0x0f,
	0x07, 0xbb, 0xce, 0x04, 0xd3, 0x30, 0x88, 0xc2, 0x7e, 0x3a, 0x35, 0xe2, 0x24, 0x4a, 0x23, 0xa4,
	0x3e, 0x50, 0xdf, 0xa7, 0x38, 0xb8, 0x25, 0xa1, 0x67, 0x0e, 0x4c, 0x23, 0x3f, 0x51, 0x2c, 0x7a,
	0x07, 0x05, 0x54, 0xec, 0x71, 0x54, 0x9b, 0x09, 0xb0, 0x6b, 0x31, 0x6f, 0x94, 0x10, 0x9c, 0x92,
	0xd1, 0x7a, 0x0f, 0xc9, 0xb0, 0xed, 0x64, 0x95, 0x28, 0x91, 0x81, 0x0a, 0xf4, 0xff, 0x76, 0xfe,
	0x89, 0x10, 0x94, 0x42, 0x1c, 0x10, 0x59, 0xe0, 0x65, 0xbe, 0x46, 0x97, 0xf0, 0x5f, 0x10, 0x85,
	0x23, 0x1f, 0x33, 0x26, 0x8b, 0x2a, 0xd0, 0x3b, 0x83, 0x13, 0x63, 0x57, 0x22, 0xc3, 0x5a, 0x13,
	0x76, 0xc1, 0xa2, 0x21, 0x6c, 0xc6, 0x13, 0xcc, 0x88, 0x2c, 0xf1, 0x26, 0xc7, 0xbb, 0x9b, 0x5c,
	0x65, 0xc7, 0xed, 0x15, 0x95, 0x85, 0x66, 0x31, 0x71, 0x28, 0x61, 0x72, 0x53, 0x05, 0xba, 0x64,
	0xe7, 0x9f, 0x48, 0x81, 0xd0, 0xc5, 0x29, 0x1e, 0x27, 0xd4, 0xb9, 0x63, 0x72, 0x4b, 0x05, 0xba,
	0x68, 0x7f, 0xa9, 0x68, 0xa7, 0xf0, 0x70, 0xc3, 0x81, 0x4d, 0x58, 0x1c, 0x85, 0x8c, 0xa0, 0x0e,
	0x14, 0xa8, 0xcb, 0x35, 0x48, 0xb6, 0x40, 0x5d, 0xed, 0x79, 0x65, 0xec, 0x3a, 0x76, 0xeb, 0x19,
	0x5b, 0xf1, 0x42, 0xce, 0x17, 0x06, 0xc5, 0x6f, 0x0c, 0x4a, 0x7f, 0x61, 0xb0, 0xf9, 0x5b, 0x83,
	0xad, 0x9f, 0x0c, 0xb6, 0x37, 0x0c, 0x1e, 0x71, 0x83, 0x65, 0x27, 0xb9, 0x41, 0x6d, 0xc8, 0x85,
	0x5d, 0x10, 0x9f, 0xec, 0x23, 0x6c, 0xdd, 0xbb, 0x8c, 0xe7, 0xbd, 0x07, 0x2f, 0x22, 0x14, 0x2d,
	0xe6, 0xa1, 0x19, 0x80, 0x9d, 0xca, 0x10, 0x9b, 0x35, 0x14, 0x56, 0x6f, 0xbd, 0x77, 0xb6, 0x07,
	0x54, 0x8c, 0x4a, 0x16, 0xa2, 0x32, 0x17, 0xf5, 0x42, 0x94, 0xa1, 0x9a, 0x21, 0xb6, 0xdb, 0xe6,
	0x21, 0x2a, 0xae, 0xeb, 0x85, 0x28, 0x43, 0x35, 0x43, 0x6c, 0xbf, 0x96, 0x73, 0xeb, 0x75, 0xa1,
	0x80, 0xf9, 0x42, 0x01, 0xef, 0x0b, 0x05, 0x3c, 0x2d, 0x95, 0xc6, 0x7c, 0xa9, 0x34, 0xde, 0x96,
	0x4a, 0xe3, 0xc6, 0xf4, 0x68, 0x3a, 0xb9, 0x1f, 0x1b, 0x4e, 0x14, 0xf4, 0xcb, 0x3f, 0x28, 0x9e,
	0xa6, 0xfe, 0xf4, 0x73, 0x99, 0x3e, 0xc6, 0x84, 0x8d, 0x5b, 0xfc, 0xb1, 0x32, 0x3f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x5f, 0x70, 0x6d, 0x26, 0xfc, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// this line is used by starport scaffolding # proto/tx/rpc
	CreateChainmon(ctx context.Context, in *MsgCreateChainmon, opts ...grpc.CallOption) (*MsgCreateChainmonResponse, error)
	UpdateChainmon(ctx context.Context, in *MsgUpdateChainmon, opts ...grpc.CallOption) (*MsgUpdateChainmonResponse, error)
	DeleteChainmon(ctx context.Context, in *MsgDeleteChainmon, opts ...grpc.CallOption) (*MsgDeleteChainmonResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateChainmon(ctx context.Context, in *MsgCreateChainmon, opts ...grpc.CallOption) (*MsgCreateChainmonResponse, error) {
	out := new(MsgCreateChainmonResponse)
	err := c.cc.Invoke(ctx, "/williamfeng323.chainmon.chainmon.Msg/CreateChainmon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateChainmon(ctx context.Context, in *MsgUpdateChainmon, opts ...grpc.CallOption) (*MsgUpdateChainmonResponse, error) {
	out := new(MsgUpdateChainmonResponse)
	err := c.cc.Invoke(ctx, "/williamfeng323.chainmon.chainmon.Msg/UpdateChainmon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteChainmon(ctx context.Context, in *MsgDeleteChainmon, opts ...grpc.CallOption) (*MsgDeleteChainmonResponse, error) {
	out := new(MsgDeleteChainmonResponse)
	err := c.cc.Invoke(ctx, "/williamfeng323.chainmon.chainmon.Msg/DeleteChainmon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// this line is used by starport scaffolding # proto/tx/rpc
	CreateChainmon(context.Context, *MsgCreateChainmon) (*MsgCreateChainmonResponse, error)
	UpdateChainmon(context.Context, *MsgUpdateChainmon) (*MsgUpdateChainmonResponse, error)
	DeleteChainmon(context.Context, *MsgDeleteChainmon) (*MsgDeleteChainmonResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateChainmon(ctx context.Context, req *MsgCreateChainmon) (*MsgCreateChainmonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChainmon not implemented")
}
func (*UnimplementedMsgServer) UpdateChainmon(ctx context.Context, req *MsgUpdateChainmon) (*MsgUpdateChainmonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateChainmon not implemented")
}
func (*UnimplementedMsgServer) DeleteChainmon(ctx context.Context, req *MsgDeleteChainmon) (*MsgDeleteChainmonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChainmon not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateChainmon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateChainmon)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateChainmon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/williamfeng323.chainmon.chainmon.Msg/CreateChainmon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateChainmon(ctx, req.(*MsgCreateChainmon))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateChainmon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateChainmon)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateChainmon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/williamfeng323.chainmon.chainmon.Msg/UpdateChainmon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateChainmon(ctx, req.(*MsgUpdateChainmon))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteChainmon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteChainmon)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteChainmon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/williamfeng323.chainmon.chainmon.Msg/DeleteChainmon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteChainmon(ctx, req.(*MsgDeleteChainmon))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "williamfeng323.chainmon.chainmon.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChainmon",
			Handler:    _Msg_CreateChainmon_Handler,
		},
		{
			MethodName: "UpdateChainmon",
			Handler:    _Msg_UpdateChainmon_Handler,
		},
		{
			MethodName: "DeleteChainmon",
			Handler:    _Msg_DeleteChainmon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chainmon/tx.proto",
}

func (m *MsgCreateChainmon) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateChainmon) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateChainmon) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Databricks != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Databricks))
		i--
		dAtA[i] = 0x30
	}
	if m.Species != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Species))
		i--
		dAtA[i] = 0x28
	}
	if m.Phase != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Phase))
		i--
		dAtA[i] = 0x20
	}
	if m.MonClass != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MonClass))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateChainmonResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateChainmonResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateChainmonResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateChainmon) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateChainmon) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateChainmon) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Databricks != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Databricks))
		i--
		dAtA[i] = 0x38
	}
	if m.Species != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Species))
		i--
		dAtA[i] = 0x30
	}
	if m.Phase != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Phase))
		i--
		dAtA[i] = 0x28
	}
	if m.MonClass != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MonClass))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateChainmonResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateChainmonResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateChainmonResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteChainmon) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteChainmon) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteChainmon) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteChainmonResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteChainmonResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteChainmonResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateChainmon) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.MonClass != 0 {
		n += 1 + sovTx(uint64(m.MonClass))
	}
	if m.Phase != 0 {
		n += 1 + sovTx(uint64(m.Phase))
	}
	if m.Species != 0 {
		n += 1 + sovTx(uint64(m.Species))
	}
	if m.Databricks != 0 {
		n += 1 + sovTx(uint64(m.Databricks))
	}
	return n
}

func (m *MsgCreateChainmonResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgUpdateChainmon) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.MonClass != 0 {
		n += 1 + sovTx(uint64(m.MonClass))
	}
	if m.Phase != 0 {
		n += 1 + sovTx(uint64(m.Phase))
	}
	if m.Species != 0 {
		n += 1 + sovTx(uint64(m.Species))
	}
	if m.Databricks != 0 {
		n += 1 + sovTx(uint64(m.Databricks))
	}
	return n
}

func (m *MsgUpdateChainmonResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteChainmon) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgDeleteChainmonResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateChainmon) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateChainmon: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateChainmon: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonClass", wireType)
			}
			m.MonClass = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MonClass |= MonClass(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Phase", wireType)
			}
			m.Phase = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Phase |= Phase(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Species", wireType)
			}
			m.Species = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Species |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Databricks", wireType)
			}
			m.Databricks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Databricks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateChainmonResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateChainmonResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateChainmonResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateChainmon) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateChainmon: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateChainmon: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonClass", wireType)
			}
			m.MonClass = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MonClass |= MonClass(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Phase", wireType)
			}
			m.Phase = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Phase |= Phase(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Species", wireType)
			}
			m.Species = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Species |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Databricks", wireType)
			}
			m.Databricks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Databricks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateChainmonResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateChainmonResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateChainmonResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteChainmon) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteChainmon: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteChainmon: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteChainmonResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteChainmonResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteChainmonResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
